version: "3.8"

services:
  api:
    build: ./backend  # path to your FastAPI Dockerfile
    container_name: chat-server
    ports:
      - "8080:8000"        # host:container
    restart: always
    networks:
      - app-net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"        # web UI on http://localhost:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata   # change to your TZ
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secret
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - app-net

  db:
    image: ankane/pgvector:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: kkoderr
      POSTGRES_PASSWORD: bhavook
      POSTGRES_DB: handbook-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  n8n_data:
  postgres_data:

networks:
  app-net:
    driver: bridge
